### ISSUE TITLE
datdaset

### ISSUE THREAD

**Issue by ermu-tech** [jzi040941/MISOnet#5]
Hi! I've noticed that you've updated your code, which is really a great job and is very useful to me.    
    About the dataset, did you use the new dataset synthesized from SWS-WSJ? How big is the dataset? If it possible, would you like to share your synthetic dataset via Google Drive or other means? (Cause I don't have SWS-WSJ dataset now ,and I try to use my dataset to run your code but it doesn't fit very well in somewhere.)
    Looking forward to your reply! Thank you !

**Comment by yuhogun0908** [comment]
Hi! 
I synthesized the dataset through SMS_WSJ github. 
The dataset is very large. hundreds of gigabytes .... 
So, I recommend you to generate the data according to the sms_wsj script

Have a nice day!

**Comment by ermu-tech** [comment]
OK! I will have a try! Thank you very much!
